__constant__ double c_tau;
__constant__ double c_h;
__constant__ double c_a;
__constant__ double c_b;
__constant__ double c_tau_to_current_time_level;
__constant__ double c_tau_to_current_time_level_to_h; // currentTimeLevel *  tau * h ( h = 1. / (p->x_size)) ;
__constant__ double c_lb;
__constant__ double c_rb;
__constant__ double c_ub;
__constant__ double c_bb;
__constant__ double c_tau_b;
__constant__ double c_pi_half;
__constant__ int c_x_length;
__constant__ int c_n;
__constant__ int c_x_st_number;
__constant__ int c_y_st_number;